<expression>        ::=     <expression2> [ <orOp> <expression> ]
<expression2>       ::=     <expression3> [ <andOp> <expression2> ]
<expression3>       ::=     <expression4> [ <comparisonOp> <expression3> ]
<expression4>       ::=     <term> { <addOp> <expression4> }
<term>              ::=     <factor> { <multiOp> <term> }
<factor>            ::=     '(' <expression> ')' | <variable> | <constant> | <boolean> | <functionCall> | <set> | '!' <expression>






//<number-expression>             ::= <eq2> | <eq1> | <eq0>
//<eq0>                           ::= '(' <number-expression> ')'
//<eq1>                           ::= (<eq0> | <eq1> | <applicable-number>) <first-priority-operator> (<eq0> | <applicable-number>)
//<eq2>                           ::= (<eq0> | <eq1> | <eq2> | <applicable-number>) <second-priority-operator> (<eq0> | <eq1> | <applicable-number>)
//<applicable-number>             ::= <name> | <function-call> | <number>
//<first-priority-operator>       ::= <mult-or-div-operator> | <bit-operator>
//<second-priority-operator>      ::= <add-or-substract-operator>



<expression> ::= <ex1> [  <expression> ]
<ex1> ::= <ex2> [ <logic-operator> <ex1> ]
<ex2> ::= <ex3> [ <comparison-operator> <ex2> ]
<ex3> ::= <ex4> [ <bit-operator> <ex3> ]
<ex4> ::= <term> [ <add-or-subtract-operator> <ex4> ]
<term> ::= <factor> [ <mult-or-div-operator> <term> ]
<factor> ::= '(' <expression> ')' | <inc-or-dec> | <name> | <type-value> | <function-call> '!' <expression>



<add-or-subtract-operator>
<mult-or-div-operator>


<expression>                    ::= <boolean-expression> | <number-expression> | <inc-or-dec> | <expression> (<logic-operator> | <bit-operator> | <comparison-operator> ) <expression>